# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'AssignmentMindera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  pod 'Toucan'
  # Pods for AssignmentMindera

  target 'AssignmentMinderaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssignmentMinderaUITests' do
    # Pods for testing
  end

end
